In [2]:
engine = create_engine(
    "mysql+pymysql://root:root@localhost:3306/TMDB"
)

print("SQLAlchemy connection created successfully!")

SQLAlchemy connection created successfully!

In [3]:
import pandas as pd
from sqlalchemy import create_engine, text

This identifies Action movies released after 2015 and helps analyse recent Action movie trends.

In [4]:
query1 = """
SELECT 
    m.title,
    m.release_date
FROM movies AS m
JOIN movie_genres AS mg
    ON m.movie_id = mg.movie_id
JOIN genres AS g
    ON mg.genre_id = g.genre_id
WHERE g.genre_name = 'Action'
  AND m.release_date > '2015-12-31'
ORDER BY m.release_date;
"""

q1_result = pd.read_sql(query1, engine)

q1_result

                            title release_date
0                    The 5th Wave   2016-01-14
1                 Kung Fu Panda 3   2016-01-23
2                     Zoolander 2   2016-02-06
3                        Deadpool   2016-02-09
4                        Triple 9   2016-02-19
..                            ...          ...
263                            F1   2025-06-25
264                      Superman   2025-07-09
265  The Fantastic 4: First Steps   2025-07-23
266            Predator: Badlands   2025-11-05
267              Mortal Kombat II   2026-05-06

[268 rows x 2 columns]

The results show which movies generated the highest revenue and the genres associated with their success.

In [5]:
query2 = """
SELECT 
    m.title,
    m.revenue,
    GROUP_CONCAT(g.genre_name SEPARATOR ', ') AS genres
FROM movies AS m
JOIN movie_genres AS mg
    ON m.movie_id = mg.movie_id
JOIN genres AS g
    ON mg.genre_id = g.genre_id
GROUP BY m.movie_id, m.title, m.revenue
ORDER BY m.revenue DESC
LIMIT 10;
"""

q2_result = pd.read_sql(query2, engine)

q2_result

,title,revenue,genres
0,Avatar,2923706026,"Adventure, Science Fiction, Action"
1,Avengers: Endgame,2799439100,"Adventure, Action, Science Fiction"
2,Avatar: The Way of Water,2334484620,"Action, Adventure, Science Fiction"
3,Titanic,2264162353,"Drama, Romance"
4,Star Wars: The Force Awakens,2068223624,"Science Fiction, Adventure, Action"
5,Avengers: Infinity War,2052415039,"Science Fiction, Adventure, Action"
6,Spider-Man: No Way Home,1921206586,"Adventure, Science Fiction, Action"
7,Zootopia 2,1868208796,"Comedy, Adventure, Animation, Mystery, Family"
8,Inside Out 2,1698863816,"Animation, Adventure, Family, Comedy"
9,Jurassic World,1671537444,"Adventure, Thriller, Science Fiction"

This compares genre-level economics and shows which genres generate the highest average revenue.

In [6]:
query3 = """
SELECT 
    g.genre_name,
    AVG(m.budget) AS average_budget,
    AVG(m.revenue) AS average_revenue
FROM movies AS m
JOIN movie_genres AS mg
    ON m.movie_id = mg.movie_id
JOIN genres AS g
    ON mg.genre_id = g.genre_id
WHERE m.budget > 0
  AND m.revenue > 0
GROUP BY g.genre_id, g.genre_name
ORDER BY average_revenue DESC;
"""

q3_result = pd.read_sql(query3, engine)

q3_result

         genre_name  average_budget  average_revenue
0         Adventure    1.113933e+08     4.014512e+08
1         Animation    8.828229e+07     3.821035e+08
2            Family    8.840877e+07     3.578708e+08
3   Science Fiction    9.786440e+07     3.356897e+08
4            Action    9.465142e+07     3.091258e+08
5           Fantasy    8.918367e+07     3.079130e+08
6            Comedy    5.465252e+07     2.230400e+08
7             Music    4.281702e+07     2.058438e+08
8           Romance    3.722695e+07     1.772269e+08
9          Thriller    5.084428e+07     1.700493e+08
10              War    5.577419e+07     1.660915e+08
11            Crime    4.655959e+07     1.543203e+08
12            Drama    4.005085e+07     1.467203e+08
13          Mystery    3.820995e+07     1.452507e+08
14          Western    5.574839e+07     1.435406e+08
15          History    5.353273e+07     1.430068e+08
16           Horror    2.575773e+07     1.155069e+08
17         TV Movie    4.200000e+06     3.746000e+03

These actors have the highest number of movie appearances in the dataset.

In [9]:
query4 = """
SELECT
    actor_name,
    COUNT(DISTINCT movie_id) AS movie_count
FROM cast
GROUP BY actor_name
ORDER BY movie_count DESC
LIMIT 10
"""

q4_result = pd.read_sql(query4, engine)

print(q4_result)

             actor_name  movie_count
0     Samuel L. Jackson           18
1     Robert Downey Jr.           13
2       Woody Harrelson           13
3             Brad Pitt           13
4    Scarlett Johansson           12
5           Johnny Depp           12
6  Benedict Cumberbatch           12
7          Ian McKellen           11
8          Mark Ruffalo           10
9           Chris Evans           10

This identifies the most active directors represented in the TMDB dataset.

In [10]:
query5 = """
SELECT 
    person_name AS director_name,
    COUNT(DISTINCT movie_id) AS movie_count
FROM crew
WHERE job = 'Director'
GROUP BY person_id, person_name
HAVING COUNT(DISTINCT movie_id) > 3
ORDER BY movie_count DESC;
"""

q5_result = pd.read_sql(query5, engine)

q5_result

         director_name  movie_count
0     Steven Spielberg           27
1           Tim Burton           19
2         Ridley Scott           19
3      Martin Scorsese           16
4      Robert Zemeckis           15
..                 ...          ...
212      Robert Eggers            4
213       Ryan Coogler            4
214    Andy Muschietti            4
215           Wes Ball            4
216  David F. Sandberg            4

[217 rows x 2 columns]

Frequently used keywords reveal common themes and storytelling trends across movies.

In [11]:
query6 = """
SELECT 
    keyword_name,
    COUNT(*) AS keyword_count
FROM movie_keywords
GROUP BY keyword_id, keyword_name
ORDER BY keyword_count DESC
LIMIT 10;
"""

q6_result = pd.read_sql(query6, engine)

q6_result

             keyword_name  keyword_count
0  based on novel or book            449
1                  sequel            416
2    duringcreditsstinger            296
3     aftercreditsstinger            242
4                  murder            176
5     based on true story            166
6           new york city            161
7                 villain            160
8            3d animation            155
9          based on comic            154

These movies had relatively high investment but comparatively low revenue, which may indicate weaker financial performance.

In [12]:
query7 = """
SELECT 
    title,
    budget,
    revenue
FROM movies
WHERE budget > (
    SELECT AVG(budget)
    FROM movies
    WHERE budget > 0
)
AND revenue < (
    SELECT AVG(revenue)
    FROM movies
    WHERE revenue > 0
)
ORDER BY budget DESC;
"""

q7_result = pd.read_sql(query7, engine)

q7_result

                                      title     budget    revenue
0                               The Marvels  274800000  206136825
1                                   Red One  250000000  185700759
2    Wake Up Dead Man: A Knives Out Mystery  210000000    4000000
3                             Green Lantern  200000000  219851172
4                                     Mulan  200000000   69965374
..                                      ...        ...        ...
283                               Rambo III   63000000  189015611
284                                Æon Flux   62000000   53321673
285                         The Equalizer 2   62000000  190400157
286                                 Shooter   61000000   95700000
287                                  2 Guns   61000000  131940411

[288 rows x 3 columns]

This identifies actors who worked in movies directed by Christopher Nolan.

In [13]:
query8 = """
SELECT DISTINCT
    c.actor_name,
    m.title
FROM cast AS c
JOIN crew AS cr
    ON c.movie_id = cr.movie_id
JOIN movies AS m
    ON c.movie_id = m.movie_id
WHERE cr.person_name = 'Christopher Nolan'
  AND cr.job = 'Director'
ORDER BY m.title, c.actor_name;
"""

q8_result = pd.read_sql(query8, engine)

q8_result

            actor_name          title
0       Christian Bale  Batman Begins
1       Cillian Murphy  Batman Begins
2          Gary Oldman  Batman Begins
3         Katie Holmes  Batman Begins
4         Ken Watanabe  Batman Begins
..                 ...            ...
95       Michael Caine   The Prestige
96        Piper Perabo   The Prestige
97        Rebecca Hall   The Prestige
98    Samantha Mahurin   The Prestige
99  Scarlett Johansson   The Prestige

[100 rows x 2 columns]

This identifies the genre with the strongest average audience rating while ensuring the result is based on enough movies.

In [14]:
query9 = """
SELECT 
    g.genre_name,
    COUNT(DISTINCT m.movie_id) AS movie_count,
    AVG(m.vote_average) AS average_rating
FROM movies AS m
JOIN movie_genres AS mg
    ON m.movie_id = mg.movie_id
JOIN genres AS g
    ON mg.genre_id = g.genre_id
GROUP BY g.genre_id, g.genre_name
HAVING COUNT(DISTINCT m.movie_id) >= 20
ORDER BY average_rating DESC
LIMIT 1;
"""

q9_result = pd.read_sql(query9, engine)

q9_result

  genre_name  movie_count  average_rating
0        War           85        7.357576

Movies with many keywords tend to have richer metadata and multiple themes associated with them.

In [15]:
query10 = """
SELECT 
    m.title,
    COUNT(mk.keyword_id) AS keyword_count
FROM movies AS m
JOIN movie_keywords AS mk
    ON m.movie_id = mk.movie_id
GROUP BY m.movie_id, m.title
ORDER BY keyword_count DESC
LIMIT 10;
"""

q10_result = pd.read_sql(query10, engine)

q10_result

                                        title  keyword_count
0                                     Smile 2             98
1                                     Taken 3             70
2                                 Silent Hill             63
3                              Twelve Monkeys             57
4              War for the Planet of the Apes             54
5                                 The Shining             52
6              Dawn of the Planet of the Apes             51
7                    How to Train Your Dragon             50
8  How to Train Your Dragon: The Hidden World             49
9   13 Hours: The Secret Soldiers of Benghazi             49